// <auto-generated />
namespace Yesla.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _this : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_this));
        
        string IMigrationMetadata.Id
        {
            get { return "201712202259264_this"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
